FROM python:3.8  
WORKDIR /projet2
COPY ./requirements.txt /projet2/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /projet2/requirements.txt
COPY ./main.py /projet2/
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
